#example 2#
Var1=35 
Var2="50"
print(type(Var2))
Var3=(int(Var2))
#print(Var1+Var2)# A Number and strings cant be added#
# in order to change the Sting to intger
Var3=int(Var2)
print(Var1+Var3)



#example 3 string concotation
a="10"
b="20"
print(a+b) #it cant be added but it can be attached like 1020
print(int(a)+int(b))# syntex to convert the string to integer and adding them 



