S=("Banglore is a beautiful city")
print(type(S)) # to know the type of variable # print(type(<any variable>)) #
print(S.upper())# to convert the word in to capitals #print(<any string variable .string operations>())
print(S.title())# to get 1st letter in capitals in every word
print(S.capitalize())# to get 1st letter in capital
print(dir(S))#to know the operations in strings # print(dir(<any string variable>)) #

#example 2
city='hyderabad'
newcity=city.upper()
print(newcity)
print(len(city))# to know the count 

